services:
  n8n:
    image: n8n_custom
    container_name: n8n
    ports:
      - 8443:8443
    environment:
      - N8N_PORT=8443
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./code:/code
    restart: unless-stopped

